### ISSUE TITLE
Example issue

### ISSUE THREAD

**Issue by dwwoelfel** [OneGraph/onegraph-examples#20]

**Comment by dwwoelfel** [comment]
Comment added from OneGraph

**Comment by i001962** [comment]
Comment added from OneGraph

**Comment by i001962** [comment]
Comment added from OneGraph @i001962 did this

**Comment by sync** [comment]
Comment added from OneGraph

**Comment by jonas-kgomo** [comment]
Comment added from OneGraphQL

**Comment by avenauche** [comment]
Comment added from OneGraph

**Comment by 0101v** [comment]
Comment added from OneGraph

**Comment by 0101v** [comment]
Comment added from OneGraph

**Comment by 0101v** [comment]
Comment added from OneGraph

**Comment by 0101v** [comment]
Comment added from OneGraph

**Comment by 0101v** [comment]
Comment added from OneGraph
